<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="51226" started-at="2017-11-26T18:49:30Z" finished-at="2017-11-26T18:50:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51226" started-at="2017-11-26T18:49:30Z" finished-at="2017-11-26T18:50:22Z">
      <class name="com.eply.tests.Login">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.eply.tests.Login@5c7fa833]" name="setup" is-config="true" duration-ms="23638" started-at="2017-11-26T20:49:30Z" finished-at="2017-11-26T20:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="tlogin()[pri:0, instance:com.eply.tests.Login@5c7fa833]" name="tlogin" is-config="true" duration-ms="0" started-at="2017-11-26T20:49:54Z" finished-at="2017-11-26T20:49:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tlogin -->
        <test-method status="FAIL" signature="loginFailed1()[pri:1, instance:com.eply.tests.Login@5c7fa833]" name="loginFailed1" duration-ms="8510" started-at="2017-11-26T20:49:54Z" finished-at="2017-11-26T20:50:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sorry, either your username or password was incorrect.] but found [Sorry, either your username or password was incorrect.To continue you must update your password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sorry, either your username or password was incorrect.] but found [Sorry, either your username or password was incorrect.To continue you must update your password.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.eply.tests.Login.loginFailed1(Login.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFailed1 -->
        <test-method status="PASS" signature="loginFailed2()[pri:2, instance:com.eply.tests.Login@5c7fa833]" name="loginFailed2" duration-ms="7965" started-at="2017-11-26T20:50:03Z" finished-at="2017-11-26T20:50:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginFailed2 -->
        <test-method status="PASS" signature="loginSucceed()[pri:99, instance:com.eply.tests.Login@5c7fa833]" name="loginSucceed" duration-ms="8082" started-at="2017-11-26T20:50:10Z" finished-at="2017-11-26T20:50:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSucceed -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.eply.tests.Login@5c7fa833]" name="tearDown" is-config="true" duration-ms="2979" started-at="2017-11-26T20:50:19Z" finished-at="2017-11-26T20:50:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.eply.tests.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
